#define offsetof_SDL_CommonEvent_type offsetof(SDL_CommonEvent, type)
#define offsetof_SDL_CommonEvent_timestamp offsetof(SDL_CommonEvent, timestamp)

#define offsetof_SDL_WindowEvent_windowID offsetof(SDL_WindowEvent, windowID)
#define offsetof_SDL_WindowEvent_event offsetof(SDL_WindowEvent, event)
#define offsetof_SDL_WindowEvent_data1 offsetof(SDL_WindowEvent, data1)
#define offsetof_SDL_WindowEvent_data2 offsetof(SDL_WindowEvent, data2)

#define offsetof_SDL_KeyboardEvent_windowID offsetof(SDL_KeyboardEvent, windowID)
#define offsetof_SDL_KeyboardEvent_state offsetof(SDL_KeyboardEvent, state)
#define offsetof_SDL_KeyboardEvent_repeat offsetof(SDL_KeyboardEvent, repeat)
#define offsetof_SDL_KeyboardEvent_keysym offsetof(SDL_KeyboardEvent, keysym)

#define offsetof_SDL_MouseMotionEvent_windowID offsetof(SDL_MouseMotionEvent, windowID)
#define offsetof_SDL_MouseMotionEvent_which offsetof(SDL_MouseMotionEvent, which)
#define offsetof_SDL_MouseMotionEvent_state offsetof(SDL_MouseMotionEvent, state)
#define offsetof_SDL_MouseMotionEvent_x offsetof(SDL_MouseMotionEvent, x)
#define offsetof_SDL_MouseMotionEvent_y offsetof(SDL_MouseMotionEvent, y)
#define offsetof_SDL_MouseMotionEvent_xrel offsetof(SDL_MouseMotionEvent, xrel)
#define offsetof_SDL_MouseMotionEvent_yrel offsetof(SDL_MouseMotionEvent, yrel)

#define offsetof_SDL_MouseButtonEvent_windowID offsetof(SDL_MouseButtonEvent, windowID)
#define offsetof_SDL_MouseButtonEvent_which offsetof(SDL_MouseButtonEvent, which)
#define offsetof_SDL_MouseButtonEvent_button offsetof(SDL_MouseButtonEvent, button)
#define offsetof_SDL_MouseButtonEvent_state offsetof(SDL_MouseButtonEvent, state)
#define offsetof_SDL_MouseButtonEvent_clicks offsetof(SDL_MouseButtonEvent, clicks)
#define offsetof_SDL_MouseButtonEvent_x offsetof(SDL_MouseButtonEvent, x)
#define offsetof_SDL_MouseButtonEvent_y offsetof(SDL_MouseButtonEvent, y)
